mail:
  from: info@ebase-sl.jp
  #to: hayakiw@ebase-sl.jp
  to: argana@ebase-sl.jp
  subject: 【Argana】お問い合わせがありました
  body_pre: お問い合わせ内容
  body_post: 以上

tokens_dir: data
token_expires: 3600

icode: utf8
ocode: utf8

cookie:
  name: jaucejptoken

template:
  INCLUDE_PATH: templates
  RELATIVE: 1
  ABSOLUTE: 1
  WRAPPER: layout.tt
  ENCODING: utf8

form:
  class: form
  submit:
    class: button
    label: 送信
  fields:
    - key: name
      label: お名前
      type: text
      length: 100
      class: w50 resp_w100
      placeholder: お名前
      top: 1
      required: 1
    - key: email
      label: Eメール
      type: text
      length: 255
      class: w50 resp_w100
      placeholder: 例 :xxx@xxx.ne.jp
      required: 1
      is_email: 1
      is_ascii: 1
    - key: hospital
      label: 病院名
      type: text
      length: 255
      class: w50 resp_w100
      placeholder: 例 :○○病院
    - key: text
      label: お問い合わせ内容
      type: textarea
      rows: 10
      length: 1024
      class: w100
      comment: ※お問い合わせ内容を入力してください。
      required: 1
